import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { requirePageAccess } from "@/lib/admin"
import { STAGE_PROBABILITY, STAGE_LABELS, getOwnerForGeo } from "@/lib/crm-config"
import { PLAYBOOK_TEMPLATES } from "@/lib/playbook-templates"
import { validateBody } from "@/lib/validate"
import { updateDealStageSchema } from "../../../_schemas"

export async function PATCH(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { error: pageErr, session } = await requirePageAccess("crm")
  if (pageErr) return pageErr

  const { id } = await params
  const v = await validateBody(request, updateDealStageSchema)
  if ("error" in v) return v.error
  const { stage: newStage, lostReason, lostNotes } = v.data

  const deal = await prisma.deal.findUnique({
    where: { id },
    include: {
      contact: {
        select: { id: true, firstName: true, lastName: true, geoZone: true, companyId: true },
      },
    },
  })

  if (!deal) {
    return NextResponse.json({ error: "Deal not found" }, { status: 404 })
  }

  const oldStage = deal.stage
  if (oldStage === newStage) {
    return NextResponse.json({ error: "Deal is already in this stage" }, { status: 400 })
  }

  const userId = session.user?.email ?? "unknown"

  // Validate closed_lost requires lostReason + lostNotes
  if (newStage === "closed_lost") {
    if (!lostReason || !lostNotes) {
      return NextResponse.json(
        { error: "Moving to closed_lost requires lostReason and lostNotes" },
        { status: 400 }
      )
    }
  }

  // Auto-update winProbability from stage
  const winProbability = STAGE_PROBABILITY[newStage] ?? 0
  const weightedValue =
    deal.dealValue != null ? deal.dealValue * winProbability : null

  const now = new Date()

  // Build the update payload
  const updateData: Record<string, unknown> = {
    stage: newStage,
    winProbability,
    weightedValue,
    daysInCurrentStage: 0,
    stageChangedAt: now,
  }

  // Closed stages
  if (newStage === "closed_won" || newStage === "closed_lost") {
    updateData.closedAt = now
  }
  if (newStage === "closed_lost") {
    updateData.lostReason = lostReason
    updateData.lostNotes = lostNotes
  }

  // Update the deal
  const updatedDeal = await prisma.deal.update({
    where: { id },
    data: updateData,
    include: {
      contact: {
        select: { id: true, firstName: true, lastName: true, email: true },
      },
      company: {
        select: { id: true, name: true },
      },
    },
  })

  const oldLabel = STAGE_LABELS[oldStage] ?? oldStage
  const newLabel = STAGE_LABELS[newStage] ?? newStage

  // Create Activity for stage change
  await prisma.activity.create({
    data: {
      type: "stage_change",
      description: `Stage changed: ${oldLabel} \u2192 ${newLabel}`,
      contactId: deal.contactId,
      dealId: id,
      performedBy: userId,
    },
  })

  // Create AuditLog entry
  await prisma.auditLog.create({
    data: {
      entityType: "deal",
      entityId: id,
      action: "stage_changed",
      field: "stage",
      oldValue: oldStage,
      newValue: newStage,
      performedBy: userId,
    },
  })

  // --- Closed Won automation ---
  if (newStage === "closed_won") {
    // Update contact lifecycleStage to "client"
    await prisma.crmContact.update({
      where: { id: deal.contactId },
      data: { lifecycleStage: "client", contactType: "client" },
    })

    // Create onboarding task
    const assignee = deal.dealOwner ?? getOwnerForGeo(deal.contact?.geoZone)
    await prisma.crmTask.create({
      data: {
        title: "Initiate KYC onboarding handoff",
        type: "other",
        priority: "high",
        dueDate: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000), // +3 days
        assignee,
        contactId: deal.contactId,
        dealId: id,
        isAutoGenerated: true,
        createdBy: userId,
      },
    })

    // Update company totalRevenue and activeDealsCount
    if (deal.companyId) {
      const companyDeals = await prisma.deal.findMany({
        where: { companyId: deal.companyId },
      })
      const totalRevenue = companyDeals
        .filter((d) => d.stage === "closed_won")
        .reduce((s, d) => s + (d.dealValue ?? 0), 0)
      const activeCount = companyDeals.filter(
        (d) => d.stage !== "closed_won" && d.stage !== "closed_lost"
      ).length
      await prisma.company.update({
        where: { id: deal.companyId },
        data: { totalRevenue, activeDealsCount: activeCount },
      })
    }
  }

  // --- Closed Lost automation ---
  if (newStage === "closed_lost") {
    // Create re-engage task due in 180 days
    const assignee = deal.dealOwner ?? getOwnerForGeo(deal.contact?.geoZone)
    await prisma.crmTask.create({
      data: {
        title: "Add to re-engage list in 6 months",
        type: "follow_up_email",
        priority: "low",
        dueDate: new Date(now.getTime() + 180 * 24 * 60 * 60 * 1000),
        assignee,
        contactId: deal.contactId,
        dealId: id,
        isAutoGenerated: true,
        createdBy: userId,
      },
    })

    // Update company activeDealsCount
    if (deal.companyId) {
      const activeCount = await prisma.deal.count({
        where: {
          companyId: deal.companyId,
          stage: { notIn: ["closed_won", "closed_lost"] },
        },
      })
      await prisma.company.update({
        where: { id: deal.companyId },
        data: { activeDealsCount: activeCount },
      })
    }
  }

  // --- Auto-initialize playbook steps for the new stage ---
  const playbookTemplate = PLAYBOOK_TEMPLATES[newStage]
  if (playbookTemplate && playbookTemplate.length > 0) {
    const existingPlaybook = await prisma.playbookStep.findFirst({
      where: { dealId: id, stage: newStage },
    })
    if (!existingPlaybook) {
      await prisma.$transaction(
        playbookTemplate.map((t, idx) =>
          prisma.playbookStep.create({
            data: {
              dealId: id,
              stage: newStage,
              title: t.title,
              description: t.description ?? null,
              isBlocking: t.isBlocking ?? false,
              order: idx,
            },
          })
        )
      )
    }
  }

  return NextResponse.json({ deal: updatedDeal })
}
