import { NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import { prisma } from "@/lib/prisma"

const TEAM_MEMBERS = [
  {
    name: "Vernon Dessy",
    initials: "VD",
    role: "CEO",
    department: "Management",
    location: "Dubai, UAE",
    email: "vernon@oxen.finance",
    phone: "+971 50 123 4567",
    telegram: "@vernondessy",
    whatsapp: "+971 50 123 4567",
    timezone: "GST",
    workHours: "09:00 - 19:00",
    entity: "Oxen",
    country: "UAE",
    startDate: new Date("2022-01-01"),
    bio: "Founder & CEO of Oxen Finance. Leading payment infrastructure across iGaming, crypto and luxury sectors.",
    avatarColor: "rgba(192,139,136,0.4)",
    order: 0,
  },
  {
    name: "Arthur Flam",
    initials: "AF",
    role: "CEO",
    department: "Management",
    location: "Brussels, Belgium",
    email: "arthur@escrowfy.com",
    phone: "+32 470 123 456",
    telegram: "@arthurflam",
    whatsapp: "+32 470 123 456",
    timezone: "CET",
    workHours: "09:00 - 18:00",
    entity: "Escrowfy",
    country: "Belgium",
    startDate: new Date("2022-03-01"),
    bio: "CEO of Escrowfy. Overseeing escrow and compliance operations across European markets.",
    avatarColor: "rgba(129,140,248,0.4)",
    order: 1,
  },
  {
    name: "Paul Louis Dessy",
    initials: "PL",
    role: "Shareholder",
    department: "Management",
    location: "Dubai, UAE",
    email: "paullouis@oxen.finance",
    timezone: "GST",
    workHours: "10:00 - 18:00",
    entity: "Oxen",
    country: "UAE",
    startDate: new Date("2022-01-01"),
    bio: "Shareholder and strategic advisor. Supporting the group's expansion in the Middle East.",
    avatarColor: "rgba(251,191,36,0.4)",
    order: 2,
  },
  {
    name: "Mickael Music",
    initials: "MM",
    role: "CTO",
    department: "Tech",
    location: "Paris, France",
    email: "mickael@oxen.finance",
    telegram: "@mickaelmusic",
    timezone: "CET",
    workHours: "09:00 - 18:00",
    entity: "Oxen",
    country: "France",
    startDate: new Date("2023-06-01"),
    bio: "Chief Technology Officer. Architecting the payment platform and internal tooling.",
    avatarColor: "rgba(52,211,153,0.4)",
    order: 3,
  },
  {
    name: "Andy Semaan",
    initials: "AS",
    role: "Sales Director",
    department: "Sales",
    location: "Dubai, UAE",
    email: "andy@oxen.finance",
    phone: "+971 55 234 5678",
    telegram: "@andysemaan",
    whatsapp: "+971 55 234 5678",
    timezone: "GST",
    workHours: "09:00 - 18:00",
    entity: "Oxen",
    country: "UAE",
    startDate: new Date("2023-01-15"),
    bio: "Sales Director managing key accounts and new business development in the iGaming and crypto sectors.",
    avatarColor: "rgba(244,114,182,0.4)",
    order: 4,
  },
  {
    name: "Aleks Ivanov",
    initials: "AI",
    role: "Account Manager",
    department: "Sales",
    location: "Dubai, UAE",
    email: "aleks@oxen.finance",
    telegram: "@aleksivanov",
    timezone: "GST",
    workHours: "09:00 - 18:00",
    entity: "Oxen",
    country: "UAE",
    startDate: new Date("2023-09-01"),
    bio: "Account Manager focused on client retention and upselling across the portfolio.",
    avatarColor: "rgba(96,165,250,0.4)",
    order: 5,
  },
  {
    name: "Luiza Santos",
    initials: "LS",
    role: "Operations Manager",
    department: "Operations",
    location: "Dubai, UAE",
    email: "luiza@oxen.finance",
    telegram: "@luizasantos",
    whatsapp: "+971 56 345 6789",
    timezone: "GST",
    workHours: "09:00 - 18:00",
    entity: "Oxen",
    country: "UAE",
    startDate: new Date("2023-04-01"),
    bio: "Operations Manager coordinating day-to-day processes, onboarding and partner relations.",
    avatarColor: "rgba(167,139,250,0.4)",
    order: 6,
  },
  {
    name: "Rudolfs Kalnins",
    initials: "RK",
    role: "Finance Manager",
    department: "Finance",
    location: "Riga, Latvia",
    email: "rudolfs@oxen.finance",
    telegram: "@rudolfskalnins",
    timezone: "CET",
    workHours: "09:00 - 18:00",
    entity: "Oxen",
    country: "Latvia",
    startDate: new Date("2023-07-01"),
    bio: "Finance Manager handling treasury, reconciliation and financial reporting.",
    avatarColor: "rgba(251,146,60,0.4)",
    order: 7,
  },
  {
    name: "Ervins Berzins",
    initials: "EB",
    role: "Senior Developer",
    department: "Tech",
    location: "Riga, Latvia",
    email: "ervins@oxen.finance",
    telegram: "@ervinsberzins",
    timezone: "CET",
    workHours: "09:00 - 18:00",
    entity: "Oxen",
    country: "Latvia",
    startDate: new Date("2023-08-01"),
    bio: "Senior Developer working on payment gateway integrations and API development.",
    avatarColor: "rgba(34,211,238,0.4)",
    order: 8,
  },
  {
    name: "Veronika Petrova",
    initials: "VP",
    role: "Compliance Officer",
    department: "Compliance",
    location: "Tallinn, Estonia",
    email: "veronika@escrowfy.com",
    telegram: "@veronikapetrova",
    timezone: "CET",
    workHours: "09:00 - 17:00",
    entity: "Escrowfy",
    country: "Estonia",
    startDate: new Date("2023-05-01"),
    bio: "Compliance Officer managing KYC/AML processes and regulatory adherence.",
    avatarColor: "rgba(248,113,113,0.4)",
    order: 9,
  },
  {
    name: "Aysegul Yilmaz",
    initials: "AY",
    role: "Compliance Analyst",
    department: "Compliance",
    location: "Istanbul, Turkey",
    email: "aysegul@escrowfy.com",
    telegram: "@aysegulyilmaz",
    timezone: "CET",
    workHours: "09:00 - 18:00",
    entity: "Escrowfy",
    country: "Turkey",
    startDate: new Date("2024-01-15"),
    bio: "Compliance Analyst supporting due diligence, screening and transaction monitoring.",
    avatarColor: "rgba(163,230,53,0.4)",
    order: 10,
  },
  {
    name: "Christel Dupont",
    initials: "CD",
    role: "Client Support Lead",
    department: "Support",
    location: "Lyon, France",
    email: "christel@oxen.finance",
    telegram: "@christeldupont",
    timezone: "CET",
    workHours: "08:00 - 17:00",
    entity: "Oxen",
    country: "France",
    startDate: new Date("2024-03-01"),
    bio: "Client Support Lead managing merchant inquiries and escalation processes.",
    avatarColor: "rgba(232,121,249,0.4)",
    order: 11,
  },
  {
    name: "Tsiaro Rakoto",
    initials: "TR",
    role: "Support Agent",
    department: "Support",
    location: "Antananarivo, Madagascar",
    email: "tsiaro@oxen.finance",
    telegram: "@tsiarorakoto",
    timezone: "CET",
    workHours: "09:00 - 18:00",
    entity: "Oxen",
    country: "Madagascar",
    startDate: new Date("2024-06-01"),
    bio: "Support Agent handling day-to-day client communications and ticket resolution.",
    avatarColor: "rgba(45,212,191,0.4)",
    order: 12,
  },
]

export async function POST() {
  const session = await auth()
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  // Only seed if no employees exist
  const existing = await prisma.employee.count()
  if (existing > 0) {
    return NextResponse.json(
      { message: `Skipped: ${existing} employees already exist. Delete all first to re-seed.` },
      { status: 200 }
    )
  }

  const created = await prisma.employee.createMany({
    data: TEAM_MEMBERS,
  })

  return NextResponse.json(
    { message: `Seeded ${created.count} team members` },
    { status: 201 }
  )
}
