import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { getOwnerForGeo, STAGE_PROBABILITY } from "@/lib/crm-config"

// ── Country → GeoZone mapping ──
const COUNTRY_GEO_MAP: Record<string, string> = {
  Malta: "Malta",
  Cyprus: "Cyprus",
  Luxembourg: "Luxembourg",
  "United Kingdom": "UK",
  UK: "UK",
  UAE: "UAE",
  "United Arab Emirates": "UAE",
  Dubai: "UAE",
  "Abu Dhabi": "UAE",
  Singapore: "Asia",
  "Hong Kong": "Asia",
  Japan: "Asia",
  China: "Asia",
  Brazil: "South America",
  Argentina: "South America",
}

const EU_COUNTRIES = new Set([
  "Austria", "Belgium", "Bulgaria", "Croatia", "Czech Republic",
  "Denmark", "Estonia", "Finland", "France", "Germany", "Greece",
  "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Netherlands",
  "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain",
  "Sweden",
])

function detectGeoZone(country: string | null | undefined): string {
  if (!country) return "Other"
  const trimmed = country.trim()
  if (COUNTRY_GEO_MAP[trimmed]) return COUNTRY_GEO_MAP[trimmed]
  // Case-insensitive lookup
  const lower = trimmed.toLowerCase()
  for (const [key, zone] of Object.entries(COUNTRY_GEO_MAP)) {
    if (key.toLowerCase() === lower) return zone
  }
  // Check EU countries
  for (const eu of EU_COUNTRIES) {
    if (eu.toLowerCase() === lower) return "Europe"
  }
  return "Other"
}

export async function POST(request: Request) {
  // ── Auth ──
  const secret = request.headers.get("x-webhook-secret")
  if (!secret || secret !== process.env.WEBSITE_WEBHOOK_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  try {
    const body = await request.json()
    const {
      firstName,
      lastName,
      email,
      phone,
      company,
      country,
      message,
      source,
      pageUrl,
    } = body

    if (!firstName || !lastName || !email) {
      return NextResponse.json(
        { error: "Missing required fields: firstName, lastName, email" },
        { status: 400 },
      )
    }

    const performedBy = "webhook:website"

    // ── 1. Duplicate Check ──
    const existing = await prisma.crmContact.findFirst({
      where: { email: { equals: email, mode: "insensitive" } },
    })

    if (existing) {
      // Log activity for re-submission
      await prisma.activity.create({
        data: {
          type: "note_added",
          description: `Inbound form re-submission from ${pageUrl || "website"}`,
          contactId: existing.id,
          performedBy,
        },
      })

      // Create follow-up task
      await prisma.crmTask.create({
        data: {
          title: "Re-engaged lead — follow up",
          type: "follow_up_email",
          priority: "high",
          dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
          assignee: existing.dealOwner ?? getOwnerForGeo(existing.geoZone),
          contactId: existing.id,
          isAutoGenerated: true,
          createdBy: performedBy,
        },
      })

      return NextResponse.json({
        success: true,
        contactId: existing.id,
        status: "existing",
      })
    }

    // ── 2. Auto-detect geoZone ──
    const geoZone = detectGeoZone(country)
    const dealOwner = getOwnerForGeo(geoZone)

    // ── 3. Create / upsert company ──
    let companyId: string | null = null
    if (company) {
      const domain = email.split("@")[1]
      const upserted = await prisma.company.upsert({
        where: { domain },
        update: {},
        create: {
          name: company,
          domain,
          geoZone,
          hqCountry: country ?? null,
        },
      })
      companyId = upserted.id
    }

    // ── 4. Create contact ──
    const contact = await prisma.crmContact.create({
      data: {
        firstName,
        lastName,
        email,
        phone: phone ?? null,
        companyId,
        country: country ?? null,
        geoZone,
        dealOwner,
        acquisitionSource: "Inbound / Website",
        acquisitionSourceDetail: source || "Website Form",
        lifecycleStage: "new_lead",
        contactType: "prospect",
        createdBy: performedBy,
      },
    })

    // ── 5. Create deal ──
    const dealName = `${firstName} ${lastName} — ${company || "Inbound"}`
    const winProbability = STAGE_PROBABILITY["new_lead"] ?? 0.05

    const deal = await prisma.deal.create({
      data: {
        dealName,
        contactId: contact.id,
        companyId,
        stage: "new_lead",
        dealOwner,
        acquisitionSource: "Inbound / Website",
        acquisitionSourceDetail: source || "Website Form",
        winProbability,
        stageChangedAt: new Date(),
        createdBy: performedBy,
      },
    })

    // ── 6. Log activity ──
    const descriptionParts = [
      `New inbound lead captured via website form.`,
      message ? `Message: "${message}"` : null,
      source ? `Source: ${source}` : null,
      pageUrl ? `Page: ${pageUrl}` : null,
    ].filter(Boolean)

    await prisma.activity.create({
      data: {
        type: "note_added",
        description: descriptionParts.join("\n"),
        contactId: contact.id,
        dealId: deal.id,
        performedBy,
      },
    })

    // ── 7. Create follow-up task ──
    await prisma.crmTask.create({
      data: {
        title: "New inbound lead — follow up within 24h",
        type: "follow_up_email",
        priority: "high",
        dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
        assignee: dealOwner,
        contactId: contact.id,
        dealId: deal.id,
        isAutoGenerated: true,
        createdBy: performedBy,
      },
    })

    // ── 8. Send Telegram notification ──
    try {
      const employee = await prisma.employee.findFirst({
        where: { name: dealOwner },
      })
      const chatId = employee?.telegramChatId
      if (chatId && process.env.TELEGRAM_BOT_TOKEN) {
        const text = [
          `🔔 *New Inbound Lead!*`,
          ``,
          `👤 ${firstName} ${lastName}`,
          company ? `🏢 ${company}` : null,
          `📧 ${email}`,
          country ? `🌍 ${country}` : null,
          message ? `📝 ${message}` : null,
          ``,
          `Source: ${source || "Website Form"}`,
          `Assigned to: ${dealOwner}`,
        ]
          .filter((line) => line !== null)
          .join("\n")

        await fetch(
          `https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              chat_id: chatId,
              text,
              parse_mode: "Markdown",
            }),
          },
        )
      }
    } catch (tgErr) {
      console.error("[Inbound Lead] Telegram notification failed:", tgErr)
    }

    // ── 9. Return success ──
    return NextResponse.json({
      success: true,
      contactId: contact.id,
      dealId: deal.id,
      assignedTo: dealOwner,
    })
  } catch (err) {
    console.error("[Inbound Lead Webhook] Error:", err)
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 },
    )
  }
}
