import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { requirePageAccess } from "@/lib/admin"

const CLOSED_STAGES = ["closed_won", "closed_lost"]

export async function POST() {
  const { error, session } = await requirePageAccess("crm")
  if (error) return error

  const now = new Date()
  const performedBy = session.user?.email ?? "system"
  const thirtyDaysAgo = new Date(now)
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30)

  const summary = {
    dealAging: 0,
    relationships: 0,
    staleTasks: 0,
    contactUpdates: 0,
    timestamp: now.toISOString(),
  }

  // ── 1. Update deal aging ──────────────────────────────────────────────
  try {
    const openDeals = await prisma.deal.findMany({
      where: { stage: { notIn: CLOSED_STAGES } },
      select: {
        id: true,
        stage: true,
        stageChangedAt: true,
        dealName: true,
        dealOwner: true,
        contactId: true,
        activities: {
          orderBy: { createdAt: "desc" },
          take: 1,
          select: { createdAt: true },
        },
      },
    })

    for (const deal of openDeals) {
      const daysInCurrentStage = Math.floor(
        (now.getTime() - new Date(deal.stageChangedAt).getTime()) / (1000 * 60 * 60 * 24)
      )

      const lastActivity = deal.activities[0]?.createdAt
      const daysSinceLastActivity = lastActivity
        ? Math.floor((now.getTime() - new Date(lastActivity).getTime()) / (1000 * 60 * 60 * 24))
        : daysInCurrentStage

      let aiDealHealth: string
      if (daysSinceLastActivity < 7) {
        aiDealHealth = "on_track"
      } else if (daysSinceLastActivity <= 14) {
        aiDealHealth = "needs_attention"
      } else {
        aiDealHealth = "at_risk"
      }

      await prisma.deal.update({
        where: { id: deal.id },
        data: {
          daysInCurrentStage,
          daysSinceLastActivity,
          aiDealHealth,
        },
      })
      summary.dealAging++
    }

    // ── 3. Auto-create tasks for stale deals ──────────────────────────────
    // (runs against the same openDeals data set to avoid a second query)
    for (const deal of openDeals) {
      const lastActivity = deal.activities[0]?.createdAt
      const daysSinceLastActivity = lastActivity
        ? Math.floor((now.getTime() - new Date(lastActivity).getTime()) / (1000 * 60 * 60 * 24))
        : Math.floor(
            (now.getTime() - new Date(deal.stageChangedAt).getTime()) / (1000 * 60 * 60 * 24)
          )

      if (daysSinceLastActivity < 7) continue

      const taskTitle = `Follow up on stale deal: ${deal.dealName}`
      const existingTask = await prisma.crmTask.findFirst({
        where: {
          dealId: deal.id,
          title: taskTitle,
          status: { not: "completed" },
        },
      })

      if (!existingTask) {
        const isHighPriority = daysSinceLastActivity >= 14
        await prisma.crmTask.create({
          data: {
            title: taskTitle,
            type: "follow_up_email",
            priority: isHighPriority ? "high" : "medium",
            dueDate: new Date(now.getTime() + 24 * 60 * 60 * 1000),
            assignee: deal.dealOwner,
            contactId: deal.contactId,
            dealId: deal.id,
            isAutoGenerated: true,
            createdBy: performedBy,
          },
        })
        summary.staleTasks++
      }
    }
  } catch (err) {
    console.error("[Daily Automation] Deal aging / stale tasks error:", err)
  }

  // ── 2. Compute relationship strength ──────────────────────────────────
  try {
    const contacts = await prisma.crmContact.findMany({
      where: {
        activities: { some: {} },
      },
      select: {
        id: true,
        activities: {
          orderBy: { createdAt: "desc" },
        },
      },
    })

    for (const contact of contacts) {
      const allActivities = contact.activities
      const recentActivities = allActivities.filter((a) => a.createdAt >= thirtyDaysAgo)

      // 1. Email frequency last 30 days: 0-25 points
      const emailsSent = recentActivities.filter(
        (a) => a.type === "email_sent" || a.type === "email_received"
      ).length
      let emailFreqPoints = 0
      if (emailsSent > 10) emailFreqPoints = 25
      else if (emailsSent >= 5) emailFreqPoints = 15
      else if (emailsSent >= 1) emailFreqPoints = 8

      // 2. Email recency: 0-25 points
      const lastEmail = allActivities.find(
        (a) => a.type === "email_sent" || a.type === "email_received"
      )
      let emailRecencyPoints = 0
      if (lastEmail) {
        const daysSinceEmail = Math.floor(
          (now.getTime() - lastEmail.createdAt.getTime()) / (1000 * 60 * 60 * 24)
        )
        if (daysSinceEmail < 3) emailRecencyPoints = 25
        else if (daysSinceEmail < 7) emailRecencyPoints = 20
        else if (daysSinceEmail < 14) emailRecencyPoints = 10
        else if (daysSinceEmail < 30) emailRecencyPoints = 5
      }

      // 3. Response rate: 0-25 points
      const totalSent = allActivities.filter((a) => a.type === "email_sent").length
      const totalReceived = allActivities.filter((a) => a.type === "email_received").length
      let responseRatePoints = 0
      if (totalSent > 0) {
        const responseRate = (totalReceived / totalSent) * 100
        if (responseRate > 80) responseRatePoints = 25
        else if (responseRate > 60) responseRatePoints = 18
        else if (responseRate > 40) responseRatePoints = 10
        else responseRatePoints = 5
      } else if (totalReceived > 0) {
        responseRatePoints = 25
      }

      // 4. Meetings last 30 days: 0-25 points
      const meetingsCount = recentActivities.filter(
        (a) => a.type === "meeting_calendly" || a.type === "meeting_manual"
      ).length
      let meetingPoints = 0
      if (meetingsCount >= 3) meetingPoints = 25
      else if (meetingsCount === 2) meetingPoints = 18
      else if (meetingsCount === 1) meetingPoints = 12

      // Total score
      const score = emailFreqPoints + emailRecencyPoints + responseRatePoints + meetingPoints

      // Map to relationship strength
      let strength: string
      if (score >= 70) strength = "strong"
      else if (score >= 40) strength = "warm"
      else if (score >= 10) strength = "cold"
      else strength = "no_relationship"

      await prisma.crmContact.update({
        where: { id: contact.id },
        data: {
          relationshipScore: score,
          relationshipStrength: strength,
        },
      })
      summary.relationships++
    }
  } catch (err) {
    console.error("[Daily Automation] Relationship computation error:", err)
  }

  // ── 4. Update contact smart fields ────────────────────────────────────
  try {
    const allContacts = await prisma.crmContact.findMany({
      select: {
        id: true,
        lastInteraction: true,
        activities: {
          select: { id: true },
        },
      },
    })

    for (const contact of allContacts) {
      const daysSinceLastContact = contact.lastInteraction
        ? Math.floor(
            (now.getTime() - new Date(contact.lastInteraction).getTime()) / (1000 * 60 * 60 * 24)
          )
        : null

      const totalInteractions = contact.activities.length

      await prisma.crmContact.update({
        where: { id: contact.id },
        data: {
          daysSinceLastContact,
          totalInteractions,
        },
      })
      summary.contactUpdates++
    }
  } catch (err) {
    console.error("[Daily Automation] Contact smart fields error:", err)
  }

  return NextResponse.json(summary)
}
