import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { requirePageAccess } from "@/lib/admin"

const CLOSED_STAGES = ["closed_won", "closed_lost"]
const FAST_FOLLOW_STAGES = ["meeting_booked", "demo", "proposal", "negotiation"]
const SLOW_FOLLOW_STAGES = ["sequence_active", "replied"]
const FAST_STALE_DAYS = 7
const SLOW_STALE_DAYS = 14

export async function POST() {
  const { error, session } = await requirePageAccess("crm")
  if (error) return error

  const now = new Date()
  const performedBy = session.user?.email ?? "system"

  // ── 1. Recalculate deal aging fields for all open deals ──
  const openDeals = await prisma.deal.findMany({
    where: { stage: { notIn: CLOSED_STAGES } },
    select: {
      id: true,
      stage: true,
      stageChangedAt: true,
      dealOwner: true,
      dealName: true,
      contactId: true,
      activities: {
        orderBy: { createdAt: "desc" },
        take: 1,
        select: { createdAt: true },
      },
    },
  })

  let dealsUpdated = 0
  let tasksCreated = 0
  let contactsUpdated = 0

  for (const deal of openDeals) {
    const daysInCurrentStage = Math.floor(
      (now.getTime() - new Date(deal.stageChangedAt).getTime()) / (1000 * 60 * 60 * 24)
    )

    const lastActivity = deal.activities[0]?.createdAt
    const daysSinceLastActivity = lastActivity
      ? Math.floor((now.getTime() - new Date(lastActivity).getTime()) / (1000 * 60 * 60 * 24))
      : daysInCurrentStage

    // Set AI deal health
    let aiDealHealth: string
    if (daysSinceLastActivity < 7) {
      aiDealHealth = "on_track"
    } else if (daysSinceLastActivity <= 14) {
      aiDealHealth = "needs_attention"
    } else {
      aiDealHealth = "at_risk"
    }

    await prisma.deal.update({
      where: { id: deal.id },
      data: {
        daysInCurrentStage,
        daysSinceLastActivity,
        aiDealHealth,
      },
    })
    dealsUpdated++

    // ── 2. Create follow-up tasks for stale deals ──
    const isFastStage = FAST_FOLLOW_STAGES.includes(deal.stage)
    const isSlowStage = SLOW_FOLLOW_STAGES.includes(deal.stage)
    const staleThreshold = isFastStage ? FAST_STALE_DAYS : isSlowStage ? SLOW_STALE_DAYS : null

    if (staleThreshold && daysSinceLastActivity >= staleThreshold) {
      // Check if there is already a pending auto-generated task for this deal
      const existingTask = await prisma.crmTask.findFirst({
        where: {
          dealId: deal.id,
          isAutoGenerated: true,
          status: "pending",
        },
      })

      if (!existingTask) {
        await prisma.crmTask.create({
          data: {
            title: `Follow up on "${deal.dealName}" — ${daysSinceLastActivity}d since last activity`,
            type: "follow_up_email",
            priority: daysSinceLastActivity >= 14 ? "high" : "medium",
            dueDate: new Date(now.getTime() + 24 * 60 * 60 * 1000), // tomorrow
            assignee: deal.dealOwner,
            contactId: deal.contactId,
            dealId: deal.id,
            isAutoGenerated: true,
            createdBy: performedBy,
          },
        })
        tasksCreated++
      }
    }
  }

  // ── 3. Recalculate smart fields for all contacts ──
  const contacts = await prisma.crmContact.findMany({
    select: {
      id: true,
      lastInteraction: true,
      activities: {
        select: { id: true },
      },
    },
  })

  for (const contact of contacts) {
    const daysSinceLastContact = contact.lastInteraction
      ? Math.floor(
          (now.getTime() - new Date(contact.lastInteraction).getTime()) / (1000 * 60 * 60 * 24)
        )
      : null

    const totalInteractions = contact.activities.length

    await prisma.crmContact.update({
      where: { id: contact.id },
      data: {
        daysSinceLastContact,
        totalInteractions,
      },
    })
    contactsUpdated++
  }

  return NextResponse.json({
    success: true,
    summary: {
      dealsUpdated,
      tasksCreated,
      contactsUpdated,
    },
  })
}
